apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springbatch-client
  tags:
    - java
  description: |
    Microsserviço responsável pelo processamento batch
  links:
    - title: Website
      url: https://github.com/mwacha/springboot-batch-client
  annotations:
    backstage.io/adr-location: docs/adr
    github.com/project-slug: mwacha/springboot-batch-client
    sonarqube.org/project-key: default/com.github.mwacha:springboot-batch-client
    jenkins.io/github-folder: microservices/springboot-batch-client/cd
spec:
  type: service
  lifecycle: production
  owner: mwacha

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name:springboot-batch-client
spec:
  type: openapi
  lifecycle: production
  owner: springboot-batch-client
  definition:
    $text: http://localhost:8091/v3/api-docs