apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-microservice          # Nome do seu microserviço
  description: "Exemplo de microsserviço Spring Boot com API Swagger"
  owner: equipe-exemplo            # Nome da equipe responsável pelo microserviço
  tags:
    - springboot
    - swagger
spec:
  type: service                    # Tipo do componente
  lifecycle: production            # Ciclo de vida do componente
  owner: mwacha         # Proprietário do serviço (adicionado aqui no spec)
  system: backend                  # Sistema ao qual o serviço pertence
  providesApis:
    - "hello-api"                  # API fornecida pelo serviço
  consumesApis: []                 # APIs consumidas (se houver)
  links:
    - url: "http://localhost:8080/swagger-ui.html"
      title: "Swagger UI"           # Link para a documentação Swagger
    - url: "http://localhost:8080/actuator"
      title: "Actuator"             # Link para o Actuator
