apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-batch-client        # Nome do seu microserviço
  description: "Microsserviço responsável pelo processamento batch"
  owner: mwacha           # Nome da equipe responsável pelo microserviço
  tags:
    - springboot
    - swagger
    - java
spec:
  type: service                    # Tipo do componente
  lifecycle: production            # Ciclo de vida do componente
  owner: mwacha         # Proprietário do serviço (adicionado aqui no spec)
  system: backend                  # Sistema ao qual o serviço pertence
  providesApis:
    - "hello-api"                  # API fornecida pelo serviço
  consumesApis: []                 # APIs consumidas (se houver)
  links:
    - url: "https://github.com/mwacha/springboot-batch-client" # Link para o repositório do GitHub
      title: "Repo"             # Título do link
    - url: "http://localhost:8091/swagger-ui.html"
      title: "Swagger UI"           # Link para a documentação Swagger
    - url: "http://localhost:8091/actuator"
      title: "Actuator"             # Link para o Actuator


---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: springboot-batch-client
spec:
  type: openapi
  lifecycle: production
  owner: mwacha
  definition:
    $text: http://localhost:8091/v3/api-docs