apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-batch-client
  tags:
    - java
  description: |
    Microsserviço responsável pelo processamento batch
#  links:
#    - title: Website
#      url: https://github.com/mwacha/springboot-batch-client
#  annotations:
#    backstage.io/adr-location: docs/adr
#    github.com/project-slug: mwacha/springboot-batch-client
#
#spec:
#  type: service
#  lifecycle: test
#  owner: mwacha
#
#---
#apiVersion: backstage.io/v1alpha1
#kind: API
#metadata:
#  name:springboot-batch-client
#spec:
#  type: openapi
#  lifecycle: production
#  owner: springboot-batch-client
#  definition:
#    $text: http://localhost:8091/v3/api-docs